### ISSUE TITLE
stock_picking_valued (Diferentes tipos de IVA)

### ISSUE THREAD

**Issue by misern2** [QubiQ/qu-stock-logistics-workflow#1]
@xavierjimenez 
El albarán valorado debería salir con los distintos tipos de IVA.
Actualmente te suma todos los ivas y te los pone el la linea de impuestos.

**Comment by xavierjimenez** [comment]
Modificado en el último commit! Se ha añadido la moneda y el mapeo de impuestos en el albarán para que los muestre en el report.
